#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <winioctl.h>
#endif

#define RA_READ CTL_CODE(0x8888, 0x888, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define RA_WRITE CTL_CODE(0x8888, 0x889, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define RA_ENABLE_SEND_LAST CTL_CODE(0x8888, 0x88a, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define RA_DISABLE_SEND_LAST CTL_CODE(0x8888, 0x88b, METHOD_BUFFERED, FILE_ANY_ACCESS)